# Generated by Django 4.0.5 on 2022-06-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_remove_comment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
