# Generated by Django 4.0.5 on 2022-06-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_alter_comment_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
    ]
