# Generated by Django 4.0.5 on 2022-06-17 14:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0012_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='', verbose_name='Content'),
        ),
    ]
