# Generated by Django 4.0.5 on 2022-06-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0014_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
