# Generated by Django 4.0.5 on 2022-06-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_info',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
