# Generated by Django 4.0.5 on 2022-06-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_info_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_info',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
