# Generated by Django 4.0.5 on 2022-06-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_thumbnail_project_info_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_info',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='image2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='image3',
            field=models.ImageField(upload_to=''),
        ),
    ]
