# Generated by Django 4.0.5 on 2022-08-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_info_image1_alter_project_info_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_info',
            name='title',
            field=models.CharField(default='first portfolio', max_length=100),
            preserve_default=False,
        ),
    ]
